-- MySQL Script generated by MySQL Workbench
-- Tue Apr  4 15:31:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema armstrong
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema armstrong
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `armstrong` DEFAULT CHARACTER SET latin1 ;
USE `armstrong` ;

-- -----------------------------------------------------
-- Table `armstrong`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armstrong`.`category` (
  `id_category` INT(11) NOT NULL AUTO_INCREMENT,
  `name_category` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `description_category` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `armstrong`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armstrong`.`article` (
  `id_article` INT(11) NOT NULL AUTO_INCREMENT,
  `name_article` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `min_description_article` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `max_description_article` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `photo1_article` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `photo2_article` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `photo3_article` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `sound1_article` VARCHAR(255) NOT NULL,
  `sound2_article` VARCHAR(255) NOT NULL,
  `sound3_article` VARCHAR(255) NOT NULL,
  `date_article` DATETIME NOT NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP(),
  `category_id_category` INT(11) NOT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `fk_article_category1_idx` (`category_id_category` ASC) VISIBLE,
  CONSTRAINT `fk_article_category1`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `armstrong`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `armstrong`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armstrong`.`contact` (
  `id_contact` INT(11) NOT NULL AUTO_INCREMENT,
  `name_contact` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `mail_contact` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `message_contact` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`id_contact`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `armstrong`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armstrong`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `login_user` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `pwd_user` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `email_user` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `autorisation_user` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
