-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 10:57:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema armstrong
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema armstrong
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `armstrong` ;
USE `armstrong` ;

-- -----------------------------------------------------
-- Table `armstrong`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armstrong`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `description_category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `armstrong`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armstrong`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `login_user` VARCHAR(45) NOT NULL,
  `pwd_user` VARCHAR(255) NOT NULL,
  `email_user` VARCHAR(45) NOT NULL,
  `permission_user` VARCHAR(45) NOT NULL,
  `category_id_category` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_category_idx` (`category_id_category` ASC) VISIBLE,
  CONSTRAINT `fk_user_category`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `armstrong`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `armstrong`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armstrong`.`article` (
  `id_article` INT NOT NULL AUTO_INCREMENT,
  `name_article` VARCHAR(45) NOT NULL,
  `min-description_article` VARCHAR(80) NOT NULL,
  `max-description_article` VARCHAR(255) NOT NULL,
  `photo1_article` VARCHAR(45) NOT NULL,
  `photo2_article` VARCHAR(45) NOT NULL,
  `photo3_article` VARCHAR(45) NOT NULL,
  `date_article` DATE NOT NULL,
  `category_id_category` INT NOT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `fk_article_category1_idx` (`category_id_category` ASC) VISIBLE,
  CONSTRAINT `fk_article_category1`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `armstrong`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `armstrong`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `armstrong`.`contact` (
  `id_contact` INT NOT NULL AUTO_INCREMENT,
  `name_contact` VARCHAR(45) NOT NULL,
  `mail_contact` VARCHAR(255) NOT NULL,
  `message_contact` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_contact`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
